function orgt(s) {
  return binl2hex(core_hx(str2binl(s), s.length * chrsz));
}
var bookConfig = {
  DownloadButtonVisible: "Hide",
  BookmarkButtonVisible: "Show",
  searchColor: "#00ffff",
  searchAlpha: 0.3,
  leastSearchChar: 0,
  CreatedBy: "华东游乐2019年新版产品电子书",
  BookTemplateName: "Float",
  loadingBackground: "#323232",
  searchPositionJS: "files/search/text_position[%d].js",
  loadingCaption: "加载中，请稍等",
  loadingCaptionColor: "#DDDDDD",
  loadingBackground: "#1F2232",
  loadingPicture: "",
  bgBeginColor: "#222222",
  bgEndColor: "#222222",
  bgMRotation: 90,
  backGroundImgURL: "files/extfile/bg.jpg",
  backgroundPosition: "Stretch",
  backgroundOpacity: 100,
  backgroundScene: "None",
  LeftShadowWidth: 100,
  LeftShadowAlpha: 1,
  RightShadowWidth: 40,
  RightShadowAlpha: 0.6,
  ShowTopLeftShadow: "Yes",
  FlipStyle: "Flip",
  FlipDirection: "0",
  autoDoublePage: "Yes",
  showMirrorSide: "Show",
  retainBookCenter: "Yes",
  isTheBookOpen: "No",
  RightToLeft: "No",
  pageBackgroundColor: "#FFFFFF",
  OriginPageIndex: 1,
  flipshortcutbutton: "Show",
  QRCode: "Hide",
  thicknessWidthType: "thick",
  thicknessColor: "#FFFFFF",
  BindingType: "side",
  HardPageEnable: "No",
  hardCoverBorderWidth: 8,
  cornerRound: 8,
  borderColor: "#FFFFFF",
  outerCoverBorder: "Yes",
  coverTexture: "none",
  HardInnerPageEnable: "No",
  totalPagesCaption: "",
  pageNumberCaption: "",
  leftMargin: 10,
  topMargin: 10,
  rightMargin: 10,
  bottomMargin: 10,
  leftMarginOnMobile: 0,
  topMarginOnMobile: 0,
  rightMarginOnMobile: 0,
  bottomMarginOnMobile: 0,
  bleedAreaLeft: "0%",
  bleedAreaTop: "0%",
  bleedAreaRight: "0%",
  bleedAreaBottom: "0%",
  maxWidthToSmallMode: "400",
  maxHeightToSmallMode: "400",
  appLogoIcon: "",
  appLogoLinkURL: "",
  appLogoOpenWindow: "Blank",
  bookTitle: "Flip HTML5",
  bookDescription: "",
  toolbarColor: "#000000",
  iconColor: "#282828",
  iconFontColor: "#ffffff",
  pageNumColor: "#ffffff",
  formBackgroundColor: "#111111",
  formFontColor: "#EEEEEE",
  logoHeight: "25",
  logoPadding: "10",
  logoTop: "8",
  FirstButtonIcon: "",
  PreviousButtonIcon: "",
  NextButtonIcon: "",
  LastButtonIcon: "",
  enablePageBack: "Hide",
  BackwardButtonIcon: "",
  ForwardButtonIcon: "",
  HomeButtonVisible: "Hide",
  HomeURL: "%first page%",
  HomeButtonIcon: "",
  AnnotationButtonVisible: "Hide",
  AnnotationButtonIcon: "",
  ShareButtonVisible: "Hide",
  ShareButtonIcon: "",
  ThumbnailsButtonVisible: "Show",
  thumbnailAlpha: 70,
  ThumbnailButtonIcon: "",
  ZoomButtonVisible: "Show",
  ZoomInButtonIcon: "",
  ZoomOutButtonIcon: "",
  FullscreenButtonVisible: "Hide",
  FullscreenButtonIcon: "",
  ExitFullscreenButtonIcon: "",
  BookMarkButtonVisible: "Hide",
  BookmarkButtonIcon: "",
  TableOfContentButtonVisible: "Hide",
  TableOfContentButtonIcon: "",
  SearchButtonVisible: "Hide",
  leastSearchChar: 3,
  searchKeywordFontColor: "#FFB000",
  SearchButtonIcon: "",
  SelectTextButtonVisible: "Hide",
  SelectTextButtonIcon: "",
  PrintButtonVisible: "Hide",
  PrintButtonIcon: "",
  printWatermarkFile: "",
  BackgroundSoundButtonVisible: "Hide",
  BackgroundSoundURL: "",
  BackgroundSoundLoop: -1,
  BackgroundSoundButtonOnIcon: "",
  BackgroundSoundButtonOffIcon: "",
  HelpButtonVisible: "Hide",
  helpContentFileURL: "",
  helpWidth: 400,
  helpHeight: 450,
  showHelpContentAtFirst: "No",
  HelpButtonIcon: "",
  InstructionsButtonVisible: "Show",
  showInstructionOnStart: "No",
  aboutButtonVisible: "Hide",
  CompanyLogoFile: "",
  AboutButtonIcon: "",
  AutoPlayButtonVisible: "Show",
  autoPlayAutoStart: "No",
  autoPlayDuration: 5,
  autoPlayLoopCount: 1,
  AutoPlayStartButtonIcon: "",
  AutoPlayStopButtonIcon: "",
  minZoomWidth: 403,
  minZoomHeight: 518,
  DownloadButtonVisible: "Hide",
  DownloadButtonIcon: "",
  DownloadURL: "",
  VideoButtonVisible: "Hide",
  VideoButtonIcon: "",
  SlideshowButtonVisible: "Hide",
  SlideshowButtonIcon: "",
  PhoneButtonVisible: "Hide",
  PhoneButtonIcon: "",
  FlipSound: "No",
  flippingTime: 0.5,
  mouseWheelFlip: "Yes",
  CurlingPageCorner: "Yes",
  updateURLForPage: "Yes",
  OpenWindow: "Blank",
  showLinkHint: "No",
  haveAdSense: "No",
  adSenseWidth: 200,
  adSenseHeight: 200,
  adSenseLeft: 50,
  adSenseTop: 50,
  adSenseClientId: "",
  googleAnalyticsID: "",
  language: "English",
  AboutAddress: "",
  AboutEmail: "support@mobissue.com",
  AboutMobile: "",
  AboutWebsite: "http://www.huadong-toy.com",
  AboutDescription: "",
  AboutAuthor: "Mobissue",
  SlideshowAutoPlay: false,
  SlideshowPlayInterval: 5,
  totalPageCount: 8,
  largePageWidth: 750,
  largePageHeight: 1624,
  normalPath: "files/page/",
  largePath: "files/large/",
  thumbPath: "files/thumb/",
};

var language = [
  {
    language: "english",
    btnFirstPage: "第一页",
    btnNextPage: "下一页",
    btnLastPage: "最后一页",
    btnPrePage: "上一页",
    btnGoToHome: "Home",
    btnDownload: "下载",
    btnSoundOn: "播放音乐",
    btnSoundOff: "关闭音乐",
    btnPrint: "打印相册",
    btnThumb: "缩略图",
    btnBookMark: "Bookmark",
    frmBookMark: "Bookmark",
    btnZoomIn: "放大图片",
    btnZoomOut: "缩小图片",
    btnAutoFlip: "自动播放",
    btnStopAutoFlip: "停止自动播放",
    btnSocialShare: "分享相册",
    btnHelp: "帮助",
    btnAbout: "关于",
    btnSearch: "Search",
    btnFullscreen: "全屏观看",
    btnExitFullscreen: "退出全屏",
    btnMore: "More",
    frmPrintCaption: "打印",
    frmPrintall: "打印所有页面",
    frmPrintcurrent: "打印当前页面",
    frmPrintRange: "打印选择页",
    frmPrintexample: "例如: 2,3,5-10",
    frmPrintbtn: "打印",
    frmShareCaption: "分享",
    frmShareLabel: "分享",
    frmShareInfo: "您可以分享到一下平台",
    frminsertLabel: "代码分享",
    frminsertInfo: "把以下代码放到您的网站即可。",
    frmaboutcaption: "Contact",
    frmaboutcontactinformation: "Contact Information",
    frmaboutADDRESS: "Address",
    frmaboutEMAIL: "Email",
    frmaboutWEBSITE: "Website",
    frmaboutMOBILE: "Mobile",
    frmaboutAUTHOR: "Author",
    frmaboutDESCRIPTION: "Description",
    frmSearch: "Search",
    frmToc: "Table Of Contents",
    btnTableOfContent: "Table Of Contents",
    btnNote: "Annotation",
    lblLast: "这已经是最后一张图片了！",
    lblFirst: "这已经是第一张图片了！",
    lblFullscreen: "点击全屏查看",
    lblName: "Name",
    lblPassword: "Password",
    lblLogin: "Login",
    lblCancel: "Cancel",
    lblNoName: "User name can not be empty.",
    lblNoPassword: "Password can not be empty.",
    lblNoCorrectLogin: "Please enter the correct user name and password.",
    btnVideo: "Video Gallery",
    btnSlideShow: "Slideshow",
    pnlSearchInputInvalid: "The search text is too short.",
    btnDragToMove: "Move by mouse drag",
    btnPositionToMove: "Move by mouse position",
    lblHelp1: "Drag the page corner to view",
    lblHelp2: "Double click to zoom in, out",
    lblCopy: "复制",
    lblAddToPage: "Add To Page",
    lblPage: "Page",
    lblTitle: "Title",
    lblEdit: "Edit",
    lblDelete: "Delete",
    lblRemoveAll: "Remove All",
    tltCursor: "Cursor",
    tltAddHighlight: "Add highlight",
    tltAddTexts: "Add texts",
    tltAddShapes: "Add shapes",
    tltAddNotes: "Add notes",
    tltAddImageFile: "Add image file",
    tltAddSignature: "Add signature",
    tltAddLine: "Add line",
    tltAddArrow: "Add arrow",
    tltAddRect: "Add rect",
    tltAddEllipse: "Add ellipse",
    lblDoubleClickToZoomIn: "双击放大图片",
    lblPages: "Pages",
    infCopyToClipboard: "您的浏览器不支持剪贴板，请s手动操作。",
    lblTitle: "Title",
    frmLinkLabel: "网址分享",
    infNotSupportHtml5: "您的浏览器不支持HTML5浏览器！",
    frmHowToUse: "How To Use",
    lblHelpPage1: "滑动手指进行翻页",
    lblHelpPage2: "请使用手势放大或双击页面",
    lblHelpPage3:
      "Click to view the table of content, bookmarks and share your books via social networks.",
    lblHelpPage4: "Add bookmarks, use search function and auto flip the book.",
    lblHelpPage5: "Open the thumbnails to overview all book pages.",
    frmQrcodeCaption:
      "Scan the bottom two-dimensional code to view with mobile phone.",
    btnPageBack: "Backward",
    btnPageForward: "Forward",
    btnLanguage: "Change Language",
    msgConfigMissing: "Configuration file is missing, unable to open the book.",
    lblDescription: "Title",
    frmTelephone: "Tel",
    btnDialing: "Call",
    lblSelectMessage: "Please copy the the text content in the text box.",
    btnSelectText: "选择文字",
    btnPhoneNumber: "Tel",
  },
];
var ols = [];
var bmtConfig = [];
var staticAd = { haveAd: false, interval: 3000, data: [] };
var videoList = [];
var slideshow = [];
var flipByAudio = { audioType: 0, audioFile: "", showPlayer: false, items: [] };
var phoneNumber = [];
var bookPlugin = null;
var fliphtml5_pages = [
  {
    l: "files/page/page0.png",
    n: "files/page/page0.png",
    t: "files/page/page0.png",
  },
  {
    l: "files/page/page1.png",
    n: "files/page/page1.png",
    t: "files/page/page1.png",
  },
  {
    l: "files/page/page2.png",
    n: "files/page/page2.png",
    t: "files/page/page2.png",
  },
  {
    l: "files/page/page3.png",
    n: "files/page/page3.png",
    t: "files/page/page3.png",
  },
  {
    l: "files/page/page4.png",
    n: "files/page/page4.png",
    t: "files/page/page4.png",
  },
  {
    l: "files/page/page5.png",
    n: "files/page/page5.png",
    t: "files/page/page5.png",
  },
  {
    l: "files/page/page6.png",
    n: "files/page/page6.png",
    t: "files/page/page6.png",
  },
  {
    l: "files/page/page7.png",
    n: "files/page/page7.png",
    t: "files/page/page7.png",
  },
];
